
  CREATE TABLE "TRIP"."MEMBER" 
   (	"M_NO" NUMBER(10,0) CONSTRAINT "MEM_NO_NN" NOT NULL ENABLE, 
	"M_PW" VARCHAR2(20 BYTE) CONSTRAINT "MEM_PW_NN" NOT NULL ENABLE, 
	"M_PCDATE" DATE CONSTRAINT "MEM_PCDATE_NN" NOT NULL ENABLE, 
	"M_MAIL" VARCHAR2(30 BYTE) CONSTRAINT "MEM_MAIL_NN" NOT NULL ENABLE, 
	"M_NAME" VARCHAR2(10 CHAR) CONSTRAINT "MEM_NAME_NN" NOT NULL ENABLE, 
	"M_ADDRESS" VARCHAR2(50 CHAR), 
	"M_MOBILE" NUMBER(12,0) CONSTRAINT "MEM_TEL_NN" NOT NULL ENABLE, 
	"M_ID" VARCHAR2(10 CHAR) CONSTRAINT "MEM_ID_NN" NOT NULL ENABLE, 
	"M_JDATE" DATE CONSTRAINT "MEM_JDATE_NN" NOT NULL ENABLE, 
	"M_ODATE" DATE, 
	"M_GRADE" VARCHAR2(10 CHAR) CONSTRAINT "MEM_GRADE_NN" NOT NULL ENABLE, 
	"M_AVATAR" NUMBER(20,0), 
	"M_POINT" NUMBER(7,0) DEFAULT 0 CONSTRAINT "MEM_POINT_NN" NOT NULL ENABLE, 
	 CONSTRAINT "MEM_NO_PK" PRIMARY KEY ("M_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MEM_MAIL_UK" UNIQUE ("M_MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MEM_TEL_UK" UNIQUE ("M_MOBILE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MEM_ID_UK" UNIQUE ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
