
  CREATE TABLE "TRIP"."SCHEDULE" 
   (	"S_NO" NUMBER(10,0), 
	"S_NAME" VARCHAR2(40 CHAR) CONSTRAINT "SCH_NAME_NN" NOT NULL ENABLE, 
	"S_SDATE" DATE CONSTRAINT "SCH_SDATE_NN" NOT NULL ENABLE, 
	"S_EDATE" DATE CONSTRAINT "SCH_EDATE_NN" NOT NULL ENABLE, 
	"S_COUNTRY" VARCHAR2(20 CHAR) CONSTRAINT "SCH_COUNTRY_NN" NOT NULL ENABLE, 
	"S_AREA" VARCHAR2(20 CHAR) CONSTRAINT "SCH_AREA_NN" NOT NULL ENABLE, 
	"S_WRITER" NUMBER CONSTRAINT "SCH_WRITER_NN" NOT NULL ENABLE, 
	"S_WDATE" DATE CONSTRAINT "SCH_WDATE_NN" NOT NULL ENABLE, 
	"S_WEDATE" DATE, 
	"S_BODY" VARCHAR2(4000 BYTE) CONSTRAINT "SCH_BODY_NN" NOT NULL ENABLE, 
	"S_RATE" NUMBER DEFAULT NULL CONSTRAINT "SCH_RATE_NN" NOT NULL ENABLE, 
	"S_DEL" CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"S_PIC" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"S_COST" NUMBER(20,0), 
	 CONSTRAINT "SCH_DEL_CK" CHECK (s_del IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "SCH_NO_PK" PRIMARY KEY ("S_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "SCH_WRITER_FK" FOREIGN KEY ("S_WRITER")
	  REFERENCES "TRIP"."MEMBER" ("M_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
