
  CREATE TABLE "TRIP"."SCHEDULEANSWER" 
   (	"SA_NO" NUMBER(10,0) CONSTRAINT "SA_NO_NN" NOT NULL ENABLE, 
	"SA_ASN" VARCHAR2(4000 BYTE) CONSTRAINT "SA_ANS_NN" NOT NULL ENABLE, 
	"SA_QNO" NUMBER(10,0) CONSTRAINT "SA_QNO_NN" NOT NULL ENABLE, 
	"SA_WRITER" NUMBER(10,0) CONSTRAINT "SA_WRITER_NN" NOT NULL ENABLE, 
	 CONSTRAINT "SA_NO_PK" PRIMARY KEY ("SA_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "SA_QNO_FK" FOREIGN KEY ("SA_QNO")
	  REFERENCES "TRIP"."SCHEDULEQUESTION" ("SQ_NO") ENABLE, 
	 CONSTRAINT "SA_WRITER_FK" FOREIGN KEY ("SA_WRITER")
	  REFERENCES "TRIP"."MEMBER" ("M_NO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 
