
  CREATE TABLE "TRIP"."SCHEDULEDINING" 
   (	"SC_DNO" NUMBER(10,0) CONSTRAINT "SCD_NO_NN" NOT NULL ENABLE, 
	"SC_SNO" NUMBER(10,0) NOT NULL ENABLE, 
	"SC_DNAME" VARCHAR2(40 CHAR) CONSTRAINT "SCD_NAME_NN" NOT NULL ENABLE, 
	"SC_DADDRESS" VARCHAR2(100 CHAR) CONSTRAINT "SCD_ADDRESS_NN" NOT NULL ENABLE, 
	"SC_DCOST" NUMBER(10,0) CONSTRAINT "SCD_COST_NN" NOT NULL ENABLE, 
	"ORDER_NO" NUMBER(10,0) CONSTRAINT "SCD_ODNO_NN" NOT NULL ENABLE, 
	"SC_DBODY" VARCHAR2(4000 BYTE), 
	 CONSTRAINT "SCD_NO_PK" PRIMARY KEY ("SC_DNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "SCD_SNO_FK" FOREIGN KEY ("SC_DNO")
	  REFERENCES "TRIP"."SCHEDULE" ("S_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
