
  CREATE TABLE "TRIP"."SCHEDULEQUESTION" 
   (	"SQ_NO" NUMBER(10,0) CONSTRAINT "SQ_NO_NN" NOT NULL ENABLE, 
	"SQ_QST" VARCHAR2(4000 BYTE) CONSTRAINT "SQ_QST_NN" NOT NULL ENABLE, 
	"SQ_MNO" NUMBER(10,0) CONSTRAINT "SQ_MNO_NN" NOT NULL ENABLE, 
	"SQ_WRITER" NUMBER(10,0) CONSTRAINT "SQ_WRITER_NN" NOT NULL ENABLE, 
	 CONSTRAINT "SQ_NO_PK" PRIMARY KEY ("SQ_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "SQ_MNO_FK" FOREIGN KEY ("SQ_MNO")
	  REFERENCES "TRIP"."SCHEDULE" ("S_NO") ENABLE, 
	 CONSTRAINT "SQ_WRITER_FK" FOREIGN KEY ("SQ_WRITER")
	  REFERENCES "TRIP"."MEMBER" ("M_NO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 
