
  CREATE TABLE "TRIP"."SCHEDULEREVIEW" 
   (	"SR_NO" NUMBER(10,0) CONSTRAINT "SR_NO_NN" NOT NULL ENABLE, 
	"SR_RATE" NUMBER(2,0) CONSTRAINT "SR_RATE_NN" NOT NULL ENABLE, 
	"SR_WDATE" DATE CONSTRAINT "SR_WDATE_NN" NOT NULL ENABLE, 
	"SR_WRITER" NUMBER(10,0) CONSTRAINT "SR_WRITER_NN" NOT NULL ENABLE, 
	"SR_HEAD" VARCHAR2(40 CHAR) CONSTRAINT "SR_HEAD_NN" NOT NULL ENABLE, 
	"SR_BODY" VARCHAR2(4000 BYTE) CONSTRAINT "SR_BODY_NN" NOT NULL ENABLE, 
	"SR_SNO" NUMBER(10,0) CONSTRAINT "SR_SNO_NN" NOT NULL ENABLE, 
	 CONSTRAINT "SR_NO_PK" PRIMARY KEY ("SR_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "SR_WRITER_FK" FOREIGN KEY ("SR_WRITER")
	  REFERENCES "TRIP"."MEMBER" ("M_NO") ENABLE, 
	 CONSTRAINT "SR_SNO_FK" FOREIGN KEY ("SR_SNO")
	  REFERENCES "TRIP"."SCHEDULE" ("S_NO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 
