
  CREATE TABLE "TRIP"."SCHEDULEUNTITLE" 
   (	"SC_UNO" NUMBER(10,0) CONSTRAINT "SCU_NO_NN" NOT NULL ENABLE, 
	"SC_SNO" NUMBER(10,0) CONSTRAINT "SCU_DSNO_NN" NOT NULL ENABLE, 
	"ORDER_NO" NUMBER(10,0) CONSTRAINT "SCU_ODNO_NN" NOT NULL ENABLE, 
	"SC_UBODY" VARCHAR2(4000 BYTE), 
	"SC_UFILE" VARCHAR2(1000 BYTE), 
	"S_DAY" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "SCU_NO_PK" PRIMARY KEY ("SC_UNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "SCU_SNO_FK" FOREIGN KEY ("SC_UNO")
	  REFERENCES "TRIP"."SCHEDULE" ("S_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
